version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "mongodb+srv://ankush:ankush2003@ankush.9quzp.mongodb.net/finacplus2"  
      USER_ACCESS_SECRET: "ankush"
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: >
      sh -c "npm i bcryptjs @types/bcryptjs && npx prisma generate && npm run dev"

  db:
    image: mongo:6
    container_name: mongodb
    restart: always
   
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  mongo_data:
